services:
  db:
    image: postgres:15
    container_name: sphera_postgres
    restart: always
    environment:
      POSTGRES_USER: user_sphera
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: sphera_db
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data
      - ./DATABASE_MIGRATION.sql:/docker-entrypoint-initdb.d/init.sql
